# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9.0

    working_directory: ~/repo

    steps:
      - checkout
      - run: ls -la
      - run: cd ./src/client && yarn install
      - run: cd ./src/client && npm rus-script bulid
